evmPrivateEncrypted: LQxXmtQGzgLrZa34IsryOKJkQklFiRiQUi-wTj6xPiWzmSJlDZm0in-CMqIT9OfhB0fzvm3ejzgyRKk27bBERSCpcBt4X8iTQ0UWPD_CrJXg5rJDm_f_BwHuRVleEDk8Zz2i2Ul5aWlt5rQaO5L5Uw

promotionComment: "###### If you enjoy the DevPool experience, please follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory) to show your support. It helps a lot!"

evmNetworkId: 100
basePriceMultiplier: 1
issueCreatorMultiplier: 3
maxConcurrentTasks: 2
maxPermitPrice: 1000

assistivePricing: true
registerWalletWithVerification: false

timeLabels:
  - name: "Time: <1 Hour"
  - name: "Time: <2 Hours"
  - name: "Time: <4 Hours"
  - name: "Time: <1 Day"
  - name: "Time: <1 Week"

priorityLabels:
  - name: "Priority: 1 (Normal)"
  - name: "Priority: 2 (Medium)"
  - name: "Priority: 3 (High)"
  - name: "Priority: 4 (Urgent)"
  - name: "Priority: 5 (Emergency)"

incentives:
  comment:
    elements:
      code: 1
      img: 0
      h1: 1
      h2: 1
      h3: 1
      h4: 1
      h5: 1
      h6: 1
      li: 0.5
      a: 1
      blockquote: 0
      i: 0
    totals:
      word: 0.1

commandSettings:
  - name: start
    enabled: true
  - name: stop
    enabled: true
  - name: wallet
    enabled: true
  - name: payout
    enabled: true
  - name: multiplier
    enabled: true
  - name: query
    enabled: true
  - name: allow
    enabled: true
  - name: autopay
    enabled: true
  - name: ask
    enabled: true
  - name: review
    enabled: true
